function [ApoI, IntKapoi] = getApoI(p)
% GETAPOI calculates the infection time-dependent apoptosis rates and 
% calculates the integral of kApoT+kApoI(tau)
%
% last revised: 2021/03/09

switch lower(p.Apo.Increase)
    case{'none'}
        ApoI     =      (p.Ex.kApoT + p.Ex.kApoI)*ones(size(p.Ex.tspan));
        IntKapoi = exp(-(p.Ex.kApoT + p.Ex.kApoI)*p.Ex.tspan);

    case{'linear'}
        ApoI     =      p.Ex.kApoT + p.Ex.kApoI.*p.Ex.tspan;
        IntKapoi = exp(- ( (p.Ex.tspan.*p.Ex.kApoT) + (0.5.*p.Ex.kApoI.*p.Ex.tspan.^2) ) );

    case{'linear_norm'} % contains kI/n, probably redundant
        tmp = p.Ex.ASS*p.Ex.tspan/max(p.Ex.tspan);
        
        ApoI     =      p.Ex.kApoT + tmp*p.Ex.kApoI;
        IntKapoi = exp(- ( (p.Ex.tspan.*p.Ex.kApoT) + (0.5*p.Ex.ASS*p.Ex.kApoI/max(p.Ex.tspan) .* p.Ex.tspan.^2) ) );                    

    case{'hill1','hill2','hill3','hill4'} % p.Ex.ASS = n // p.Ex.AST = K_h = H
        p.Ex.ASS = str2double(p.Apo.Increase(end));

        ApoI_tau = p.Ex.kApoI .* p.Ex.tspan.^p.Ex.ASS ./(p.Ex.AST^p.Ex.ASS + p.Ex.tspan.^p.Ex.ASS);
        ApoI     = p.Ex.kApoT + ApoI_tau;

        % varying hill coefficients (interger) generate different integral solutions
        if (strcmp(p.Apo.Increase(end),'1'))
            IntKapoi = exp(-( ...
                p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI.*( ...
                    p.Ex.tspan + p.Ex.AST.*log(p.Ex.AST./(p.Ex.AST+p.Ex.tspan)) ...
                ) ...
            ) );                     

        elseif (strcmp(p.Apo.Increase(end),'2'))
            IntKapoi = exp(-( ...
                p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI.*( ...
                    p.Ex.tspan - p.Ex.AST.*atan(p.Ex.tspan./p.Ex.AST) ...
                ) ...
            ) );

        elseif (strcmp(p.Apo.Increase(end),'3'))                                                                
            IntKapoi = exp(-( ...
                p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI./6.*( ...
                    6.*p.Ex.tspan + p.Ex.AST.*( ...
                        log(abs(p.Ex.tspan.^2 - p.Ex.AST.*p.Ex.tspan + p.Ex.AST.^2)./(p.Ex.AST+p.Ex.tspan).^2) ...
                        + 2.*sqrt(3).*(atan(-1./sqrt(3)) - atan((2.*p.Ex.tspan-p.Ex.AST)./(sqrt(3).*p.Ex.AST))) ...
                    ) ...
                ) ...
            ) );                                         

        elseif (strcmp(p.Apo.Increase(end),'4'))                                                                                              
            IntKapoi = exp(-( ...
                p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI.*p.Ex.tspan - 2^(-2.5).*p.Ex.AST.*p.Ex.kApoI.*( ...
                    log((p.Ex.tspan.^2+sqrt(2).*p.Ex.AST.*p.Ex.tspan+p.Ex.AST.^2)./(abs(p.Ex.tspan.^2-sqrt(2).*p.Ex.AST.*p.Ex.tspan+p.Ex.AST.^2))) ...
                    + 2.*(atan((sqrt(2).*p.Ex.tspan+p.Ex.AST)./p.Ex.AST) + atan((sqrt(2).*p.Ex.tspan-p.Ex.AST)./p.Ex.AST)) ...
                ) ...
            ) );                      
        end
        
    case{'gombertz'} % p.Ex.ASS = c // p.Ex.AST = b
        ApoI_tau = p.Ex.kApoI.*exp(-p.Ex.ASS.*exp(-p.Ex.AST.*p.Ex.tspan));
        ApoI     = p.Ex.kApoT + ApoI_tau;
        
        IntKapoi = exp(-( ...
            p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI./p.Ex.AST.*( ...
                expint(p.Ex.ASS*exp(-p.Ex.AST.*p.Ex.tspan)) - expint(p.Ex.ASS) ...
            ) ...
        ) );
    
    case{'sigmoidal'}                  
        ApoI_tau = p.Ex.kApoI./(1+exp(- p.Ex.ASS*(p.Ex.tspan - p.Ex.AST) ) );
        ApoI     = p.Ex.kApoT + ApoI_tau;

        IntKapoi = exp(-( ...
            p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI/p.Ex.ASS.*( ...
                log( (exp(-p.Ex.ASS*(p.Ex.tspan-p.Ex.AST))+1) ./ (exp(p.Ex.ASS*p.Ex.AST)+1) ) ...
                    + p.Ex.ASS*p.Ex.tspan ...
            ) ...
        ) ); 

    case{'normal_distribution'}       
        ApoI_tau = p.Ex.kApoI .* 0.5 .* (1 + erf((p.Ex.tspan-p.Ex.AST)./p.Ex.ASS./sqrt(2)));
        ApoI     = p.Ex.kApoT + ApoI_tau;
        
        IntKapoi = exp(-(...
            p.Ex.tspan.*p.Ex.kApoT + 0.5.*p.Ex.kApoI.*...
              ( p.Ex.tspan ...
                + ( (p.Ex.tspan-p.Ex.AST).*erf((p.Ex.tspan-p.Ex.AST)./p.Ex.ASS./sqrt(2))...
                    + p.Ex.ASS.*sqrt(2)./sqrt(pi).*exp(-((p.Ex.tspan-p.Ex.AST).^2)./2./p.Ex.ASS.^2)...
                  ) ...
                - ( -p.Ex.AST.*erf((-p.Ex.AST)./p.Ex.ASS./sqrt(2))...
                                + p.Ex.ASS.*sqrt(2)./sqrt(pi).*exp(-(p.Ex.AST.^2)./2./p.Ex.ASS.^2)...
                  ) ...
              ) ...
        ) );

    otherwise
        error('Error: Apoptosis rate increase must be defined correctly!');
end 

